#### 함수복습

In [ ]:
# 소수판별 is_prime()
[2,3,4,5,6,7,8,9] -> [True, True, False, True, False, True, False, False]

In [6]:
is_prime([2,3,4,5,6,7,8,9])

[True, True, False, True, False, True, False, False]

In [5]:
def is_prime(num_list):
    result = []
    for num in num_list:
        isprime = True
        for i in range(2, num):
            if num % i == 0:
                isprime = False
                break
        result.append(isprime)
    return result

In [3]:
num = 7 # 2... 3... 4... 5.... 

isprime = True
for i in range(2, num):
    if num % i == 0:
        isprime = False
        break

print(isprime)

True


In [25]:
# 등수 구하기 - 평균점수(영어점수, 수학점수)
def rank(score):
    avg = [sum(s)/len(s) for s in score]
    avg_sort = sorted(avg, reverse=True)
    result = [avg_sort.index(i)+1 for i in avg] # enumerate로 속도 향상!!!!
    return result

In [26]:
score1 = [[80, 70], [90, 50, 30], [40, 70, 100, 100], [50, 80]]
rank(score1) # [1, 2, 4, 3]

[2, 4, 1, 3]

In [22]:
score2 = [[80, 70], [70, 80], [30, 50], [90, 100], [100, 90], [100, 100], [10, 30]]
rank(score2) # [4, 4, 6, 2, 2, 1, 7]

[75.0, 75.0, 40.0, 95.0, 95.0, 100.0, 20.0]
[100.0, 95.0, 95.0, 75.0, 75.0, 40.0, 20.0]
[4, 4, 6, 2, 2, 1, 7]


### 모듈

In [ ]:
import sys

for path in sys.path:
    print(path)

In [ ]:
import random

random.randint(1, 100)
random.randrange(1, 5)
random. sample([1,2,3], 1)

In [48]:
import random as r

r.randint(1, 100)
r.randrange(1, 5)
r. sample([1,2,3], 1)

[3]

In [45]:
from random import randint, randrange

randint(1, 100)
randrange(1, 5)

3

In [ ]:
from random import *
from math import *

randint(1, 100)
randrange(1, 5)
sample([1,2,3], 1)

[3]

#### 사용자 정의 모듈

In [54]:
import importlib
import mymodule as mm

importlib.reload(mm)

print(mm.my_add(11, 5))
print(mm.my_sub(11, 5))

mymodule안에서의 __name__: mymodule
16
6


In [ ]:
# 행운번호 추첨기 - 6개에 보너스 번호 1개, 1~45 중에서 6개의 중복되지 않는 숫자
# [1, 2, 3, 4, 5, 6]

In [90]:
import random as r

result = []
while len(result) < 6:
    num = r.randint(1, 45)
    if num not in result:
        result.append(num)

print(result)

[7, 21, 20, 33, 44, 5]


In [ ]:
random.sample([x for x in range(1, 46, 1)], 6)

### 클래스

In [92]:
class Person:
    def __init__(self, name, age ):
        self.name = name
        self.age = age

    def walk(self):
        print(f'{self.name}이 걸어가요')

In [95]:
person1 = Person("박지민", 31)

In [99]:
person2 = Person("전정국", 29)

In [97]:
print(type(person1))

<class '__main__.Person'>


In [98]:
person1.walk()

박지민이 걸어가요


In [102]:
person1.age

31

In [100]:
person2.walk()

전정국이 걸어가요


In [ ]:
# 상속
class NewPerson(Person):
    def fly(self): # 기능확장
        print(f'{self.name}이 하늘을 날아요')
    def walk(self): # 메서드 오버라이딩
        print(f'{self.name}이 아주 빠르게 걸어가요')

In [117]:
person3 = NewPerson("민윤기", 33)

In [118]:
person3.walk()

민윤기이 아주 빠르게 걸어가요


In [129]:
class NewNewPerson(Person):
    populataion = 0

    def __init__(self, name, age, hobby ):
        super().__init__(name, age)
        self.hobby = hobby
        NewNewPerson.populataion += 1

    def fly(self): # 기능확장
        print(f'{self.name}이 하늘을 날아요')

    def walk(self): # 메서드 오버라이딩
        print(f'{self.name}이 아주 빠르게 걸어가요')

    def introduce(self):
        print(f'{self.name}의 취미는 {self.hobby}입니다. ')

In [130]:
person1 = NewNewPerson("전정국", 31, "춤추기")
person2 = NewNewPerson("박지민", 29, "운동하기")
person3 = NewNewPerson("김태형", 33, "노래부르기")

In [139]:
person3.populataion

3

### 넘파이

In [140]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.1'

In [4]:
alist = [1,2,3,4,5]

In [6]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5]
<class 'list'>


In [16]:
ar1 = np.array([1, 2, 3, 4, 5])

In [19]:
ar1.shape

(5,)

In [17]:
print(ar1)
print(type(ar1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
ar1.dtype

dtype('int64')

In [12]:
ar2 = np.array([1., 2.2, 3.3, 4., 5.])

In [13]:
ar2.dtype

dtype('float64')

In [14]:
ar2 = np.array([1, 2.2, 3.3, 4, 5])

In [15]:
print(ar2)
print(type(ar2))
ar2.dtype

[1.  2.2 3.3 4.  5. ]
<class 'numpy.ndarray'>


dtype('float64')

In [20]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10, 11, 12]])

In [21]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr2.ndim

2

In [30]:
arr2.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
arr2.shape

(3, 4)

In [32]:
arr2.reshape(2, -1, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
x = np.arange(1, 10)

In [35]:
y = np.zeros_like(x)

In [34]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
import time

size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)

start_time = time.time()
result_list = [x * 2 for x in py_list]
end_time = time.time()
print(f'Python 리스트 연산: {end_time - start_time:.5f}초')

start_time = time.time()
result_array = np_array * 2
end_time = time.time()
print(f'Numpy 배열 연산: {end_time - start_time:.5f}초')

Python 리스트 연산: 0.12472초
Numpy 배열 연산: 0.00405초


In [56]:
alist = np.array([1, 2, 3, 4, 5])
blist = np.array([6, 7, 8, 9, 10])

In [57]:
alist == 2

array([False,  True, False, False, False])

In [42]:
alist + blist

array([ 7,  9, 11, 13, 15])

In [45]:
alist / blist

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [54]:
arr = [1, 2, 3, 4, 5]
brr = [6, 7, 8, 9, 10]

In [40]:
arr + brr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [47]:
arr + 1

TypeError: can only concatenate list (not "int") to list

In [55]:
arr == 2

False

In [46]:
alist + 1

array([2, 3, 4, 5, 6])

In [50]:
alist / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [51]:
data = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

answer = []
for i in data:
    answer.append(i *2)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [52]:
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
xlist = [[0, 1, 2], [3, 4, 5]]

In [69]:
xlist[0, 0]

TypeError: list indices must be integers or slices, not tuple

In [59]:
a = np.array([[0, 1, 2], [3, 4, 5]])

In [65]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
print(a[0][1])

1


In [64]:
print(a[0, 1])

1


In [74]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [75]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
a[ : , : 2]

array([[0, 1],
       [4, 5]])

In [73]:
a[0,:3 ]

array([0, 1, 2])

In [84]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True ])

a[idx]

IndexError: boolean index did not match indexed array along axis 0; size of axis is 10 but size of corresponding boolean axis is 5

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# [0, 2, 4, 6, 8]

In [83]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [82]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [85]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])

a[idx]

array([11, 33, 55, 77, 99])

In [87]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([7, 2, 1])
a[idx]

array([88, 33, 22])

In [88]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
a[[2, 0, 1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [89]:
a[: ,[True, False, False, True ]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [91]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [98]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [95]:
x % 4 == 1

array([ True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False])